- id: pyrefly-check
  name: pyrefly check
  description: "Run `pyrefly check` with user-specified version via additional_dependencies."
  entry: pyrefly check
  language: python
  types_or: [python, pyi]
  pass_filenames: false
  require_serial: true
  stages: [pre-commit, pre-merge-commit, pre-push, manual]
